export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const AGREGAR_TAREA_OK = "AGREGAR_TAREA_OK";
export const AGREGAR_TAREA_ERROR = "AGREGAR_TAREA_ERROR";

export const OBTENER_TAREAS = "OBTENER_TAREAS"
export const OBTENER_TAREAS_ERROR = "OBTENER_TAREAS_ERROR"

export const ELIMINAR_TAREA = "ELIMINAR_TAREA"
export const ELIMINAR_TAREA_ERROR = "ELIMINAR_TAREA_ERROR"
export const ELIMINAR_TAREA_OK = "ELIMINAR_TAREA_OK"

export const EDITAR_TAREA = "EDITAR_TAREA"
export const EDITAR_TAREA_ERROR = "EDITAR_TAREA_ERROR"
export const EDITAR_TAREA_OK = "EDITAR_TAREA_OK"
export const EDICION_TAREA = "EDICION_TAREA"